export {
  mdiArrowLeft,
  mdiBullhornOutline,
  mdiChartLine,
  mdiCheckCircleOutline,
  mdiCloseCircleOutline,
  mdiDatabaseSync,
  mdiDeleteOutline,
  mdiEyeOutline,
  mdiFileDocumentEditOutline,
  mdiFileDocumentOutline,
  mdiFilterOutline,
  mdiFormatListBulletedSquare,
  mdiLayersTriple,
  mdiLogin,
  mdiLogoutVariant,
  mdiOpenInNew,
  mdiPencil,
  mdiPlayCircleOutline,
  mdiPlus,
  mdiPublish,
  mdiRefresh,
  mdiSync,
  mdiTarget,
  mdiTune,
  mdiViewDashboardOutline,
} from '@mdi/js'
